language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t tnduc91/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true tnduc91/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-970952366686"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
