language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t tnduc91/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true tnduc91/docker-react npm run test
